// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/tagbuilder/tagbuilder.proto

/*
Package tagbuilder is a generated protocol buffer package.

It is generated from these files:
	rpc/tagbuilder/tagbuilder.proto

It has these top-level messages:
	Merchant
	Tag
	TagContainer
*/
package tagbuilder

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Merchant for
type Merchant struct {
	MerchantId int32 `protobuf:"varint,1,opt,name=merchantId" json:"merchantId,omitempty"`
}

func (m *Merchant) Reset()                    { *m = Merchant{} }
func (m *Merchant) String() string            { return proto.CompactTextString(m) }
func (*Merchant) ProtoMessage()               {}
func (*Merchant) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Merchant) GetMerchantId() int32 {
	if m != nil {
		return m.MerchantId
	}
	return 0
}

type Tag struct {
	Tag string `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
}

func (m *Tag) Reset()                    { *m = Tag{} }
func (m *Tag) String() string            { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()               {}
func (*Tag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Tag) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

// Tracking
type TagContainer struct {
	MerchantId int32  `protobuf:"varint,1,opt,name=merchantId" json:"merchantId,omitempty"`
	Tags       []*Tag `protobuf:"bytes,2,rep,name=tags" json:"tags,omitempty"`
}

func (m *TagContainer) Reset()                    { *m = TagContainer{} }
func (m *TagContainer) String() string            { return proto.CompactTextString(m) }
func (*TagContainer) ProtoMessage()               {}
func (*TagContainer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TagContainer) GetMerchantId() int32 {
	if m != nil {
		return m.MerchantId
	}
	return 0
}

func (m *TagContainer) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*Merchant)(nil), "Merchant")
	proto.RegisterType((*Tag)(nil), "Tag")
	proto.RegisterType((*TagContainer)(nil), "TagContainer")
}

func init() { proto.RegisterFile("rpc/tagbuilder/tagbuilder.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2f, 0x2a, 0x48, 0xd6,
	0x2f, 0x49, 0x4c, 0x4f, 0x2a, 0xcd, 0xcc, 0x49, 0x49, 0x2d, 0x42, 0x62, 0xea, 0x15, 0x14, 0xe5,
	0x97, 0xe4, 0x2b, 0x69, 0x71, 0x71, 0xf8, 0xa6, 0x16, 0x25, 0x67, 0x24, 0xe6, 0x95, 0x08, 0xc9,
	0x71, 0x71, 0xe5, 0x42, 0xd9, 0x9e, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x48, 0x22,
	0x4a, 0xe2, 0x5c, 0xcc, 0x21, 0x89, 0xe9, 0x42, 0x02, 0x5c, 0xcc, 0x25, 0x89, 0xe9, 0x60, 0x79,
	0xce, 0x20, 0x10, 0x53, 0xc9, 0x83, 0x8b, 0x27, 0x24, 0x31, 0xdd, 0x39, 0x3f, 0xaf, 0x24, 0x31,
	0x33, 0x2f, 0xb5, 0x88, 0x90, 0x41, 0x42, 0x12, 0x5c, 0x2c, 0x25, 0x89, 0xe9, 0xc5, 0x12, 0x4c,
	0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x2c, 0x7a, 0x21, 0x89, 0xe9, 0x41, 0x60, 0x11, 0x23, 0x43, 0x2e,
	0xae, 0x90, 0xc4, 0x74, 0x27, 0x88, 0x13, 0x85, 0x94, 0xb9, 0xd8, 0xdd, 0x53, 0x4b, 0x42, 0x12,
	0xd3, 0x8b, 0x85, 0x38, 0xf5, 0x60, 0xce, 0x94, 0xe2, 0xd5, 0x43, 0xb6, 0xcc, 0x89, 0x27, 0x8a,
	0x0b, 0xe1, 0xab, 0x24, 0x36, 0xb0, 0xb7, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x21,
	0x67, 0x76, 0xf9, 0x00, 0x00, 0x00,
}
