# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/nwingert/twirp-demo
    steps:
      - checkout

      # Make sure you grab the latest version
      run: mkdir /tmp/download
      run: (cd /tmp/download && curl -OL https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip)

      # Unzip
      unzip protoc-3.5.1-linux-x86_64.zip -d protoc3

      # Move protoc to /usr/local/bin/
      sudo mv protoc3/bin/* /usr/local/bin/

      # Move protoc3/include to /usr/local/include/
      sudo mv protoc3/include/* /usr/local/include/

      # Optional: change owner
      sudo chwon [user] /usr/local/bin/protoc
      sudo chwon -R [user] /usr/local/include/google
      - run: go get -v -t -d ./...
      - run: go test -v ./...